### ISSUE TITLE
[BUG] Bot works, but actually chatting does not

### ISSUE THREAD

**Issue by SonicandTailsCD** [spyingcreeper09/Minecraft-Protocol-Basic-Chat-Bot#1]
![Screenshot from 2024-05-02 19:55:22](https://github.com/spyingcreeper09/Minecraft-Protocol-Basic-Chat-Bot/assets/80169260/ff93792e-7ad6-4a2f-8dd1-eefb09e1e174)
The bot simply does not react to messages. Any fix? Or can I maybe help you fix the problem? :)

**Comment by spyingcreeper09** [comment]
Thanks for reporting it. i thought i had fixed this before publishing. if you have a fix go ahead and update it, if not then i will update it when i get the chance

**Comment by SonicandTailsCD** [comment]
No problem! That's what I like to do :)
I'll try fixing this mistake for you and upload a pull request.

**Comment by SonicandTailsCD** [comment]
I uploaded a bug fix for you in #2. 
This issue is resolved :)
